import { setLang } from './i18n.js';
import { toggleMusic, toggleSound } from './audio.js';
import {
  initApp,
  openSetup,
  openRules,
  closeRules,
  closeRulesOnBackdrop,
  selectMode,
  selectOpponentType,
  selectBotDifficulty,
  selectRoundCount,
  startFromSetup,
  closeDailyInfoOnBackdrop,
  startDailyChallenge,
  closeDailyInfo,
  exportResultCard,
  handleAgainButton,
  handleMenuButton,
  playLatestMatchReplay,
  refreshLocalizedUi,
  syncAvailableModes,
  updateModeBadge,
  setResultPresentation,
  syncRankedLockState,
  syncLocalizedOpponentName,
} from './app.js';

Object.assign(window, {
  setLang,
  toggleMusic,
  toggleSound,
  openSetup,
  openRules,
  closeRules,
  closeRulesOnBackdrop,
  selectMode,
  selectOpponentType,
  selectBotDifficulty,
  selectRoundCount,
  startFromSetup,
  closeDailyInfoOnBackdrop,
  startDailyChallenge,
  closeDailyInfo,
  exportResultCard,
  handleAgainButton,
  handleMenuButton,
  playLatestMatchReplay,
  refreshLocalizedUi,
  syncAvailableModes,
  updateModeBadge,
  setResultPresentation,
  syncRankedLockState,
  syncLocalizedOpponentName,
});

initApp();
